# Cleanup: remove 191 old (virtual) villa pages and stale area pages.
# Run: powershell -ExecutionPolicy Bypass -File cleanup-virtual-villas.ps1
$ErrorActionPreference = "Continue"
cd $PSScriptRoot

# --- old villa pages (not our properties) ---
Remove-Item -LiteralPath "villa\12br-ubud-family-villas-home-gymspa-yoga-shala" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\1br-private-pool-villa-kepompong-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\1br-tropical-villa-w-private-pool-in-uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\2br-the-menuai-bali-villas-canggu-near-beach" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\3br-family-villa-in-ubud-pool-gym-style" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\3br-luxury-private-pool-villa-nusa-dua-kecamatan-kuta-selatan" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\3br-private-pool-villa-ricefield-view-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\4br-ubud-pool-home-cinema-yoga-deck-ricefield-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\5br-family-villa-wpool-spa-beachy-vibe-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\ahava-6br-family-villa-winfinity-pool-gym-spa" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\alba-private-1br-villa-near-ubud-center" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\alcove-boutique-private-pool-villa-d-uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\alcove-boutique-villa-a-1br-uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\alcove-boutique-villa-c-1br-uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\aloha-6br-family-villa-wprivatepool-gym-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\amartya-22" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\amartya-f9" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\anastheo-modern-3br-villa-with-stunning-views" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\andrea-2br-villa-with-lush-jungle-view-of-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\azzurra-spacious-4br-villa-600m-to-balangan-beach" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\bale-dauh-2br-villa-wsunken-lounge-infinitypool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\balinese-zen-tranquil-2br-retreat-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\blackrock-5br-tranquil-retreat-in-ubuds-heart" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\bloom-1br-joglo-900m-to-beach-in-canggu-center" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\brand-new-3br-villa-with-private-pool-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\calamansi-6br-valley-villa-with-jungle-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\casa-gaia-1-1br-villa-between-canggu-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\casa-gaia-2-1br-villa-between-canggu-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\casa-gaia-3-1br-villa-between-canggu-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\casa-gaia-5-1br-villa-between-canggu-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\casa-gaia-6-1br-villa-between-canggu-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\casa-lampara-2br-oasis-steps-from-pererenan-beach" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\cinta-ubud-romantic-1br-villa-infinity-pool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\cocktail-and-dreams-5br-wprivate-poolmassage-bed" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\costa-breezy-3br-villa-600m-to-balangan-beach" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\cove-retreat-5br-villa-with-gym-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\cozy-2br-in-canggu-berawa-5-mins-to-the-beach-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\cozy-private-suite-in-central-berawa-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\disini-villas" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\dream-meditation-6br-family-villa-w-pool-gym" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\dream-nest-2br-w-private-pool-outdoor-bathtub" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\el-dorado-serene-3br-oasis-in-ubud-w-jungle-views" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\elegant-2br-private-pool-villa-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\elegant-modern-4br-retreat-in-the-heart-of-berawa-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\est-paradise-3br-serene-jungle-retreat-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\golden-lion-embrace-3br-villa-with-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\hanuman-teges-5br-family-villas-wjungle-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\harper-4br-family-villa-w-kids-room-in-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\homala-2br-cliffside-luxury-villa-w-infinity-pool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\jeromaia-5br-villa-wlush-jungle-paddy-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\joy-boutique-5br-family-villa-wricefields-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\jungle-paradise-5br-villa-w-gym-ubud-center" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\kaia-raya-surf-lodge" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\kanginlane" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\laguna-2br-villa-w-green-lush-jungle-near-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\leya-paradise-2br-villa-winfinity-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\lou-tirta-empul-6-br-villa-w-pool-jungle-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\louise-hanna-2br-natures-embrace-valley-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\luna-lotus-5br-family-villa-wpool-paddy-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\luxe-2br-pool-villa-canggu-sun" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\luxury-1br-private-pool-villa-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\magma-1" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\magma-3" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\magma-4" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\memandu-4-br-family-villa-winfinity-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\moana-3br-ubud-villa-w-pool-yoga-shala" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\modern-artistic-5br-haven-in-canggu-berawa-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\moksha-1-private-ensuite-room-in-uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\moksha-2-private-suite-near-beaches-in-uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\moksha-3-private-room-near-uluwatu-beaches" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\montana-6br-family-villa-gym-infinity-pool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\natha-swari-1br-private-villa-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\nathaubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\new-2br-luxury-retreat-canggu-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\new-kavana-elan-5-mins-to-berawa-beach-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\new-kavana-solea-5-mins-to-berawa-beach-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\new-modern-1br-villa-w-private-pool-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\new-tropical-retreat-2br-villa-in-seminyak-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\orion-5br-villa-in-ubud-pool-and-jungle-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\padma-putih-5br-20m-pool-twin-beds-massage" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\palm-paradise-5br-infinity-pool-villa-ubud-center" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\pool-bar-5br-infinity-pool-villa-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\private-deluxe-villa-20-m-infinitypool-ocean-front" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\private-peaceful-berawa-suite-near-beach-cafes-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\putga-5br-family-villa-winfinity-pool-spa-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\reva-2br-enchanted-rice-grove-villa-winfinitypool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\rumah-jiwa" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\sakaya-modern-3br-villa-w-private-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\samadhi-villas-aruna" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\santana-2br-nature-serenity-in-ubuds-heart" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\sarang-cocoon-ubud-2br-villa-with-infinity-pool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\semesta-1br-honeymoon-villa-winfinity-pool-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\seminyak-3br-private-pool-villa-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\sira-rosa-villa-2br-with-rooftop-oasis-uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\solis-2br-romantic-hideaway-w-gym-nature-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\spacious-5br-modern-simplicity-near-canggus-best-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\stylish-2br-villa-private-pool-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\stylish-3br-pool-villa-100m-from-batu-bolong-beach-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\sunrise-2br-stylish-villa-with-infinity-pool-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\sunset-serenity" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\surya-2br-jungle-paradise-relaxing-retreat-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\symphony-white-6br-villa-w-private-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\tanah-yang-jauh-5br-family-villa-with-pool-gym" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\taurus-5br-private-luxury-villa-canggu-5-min-beach" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\tavisha-5br-family-villa-winfinity-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\tchikobo-3br-villa-w-jungle-rice-field-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\teva-5br-villa-tropical-tranquility-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\the-beauty-riptide" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\the-blue-parrot-6br-family-villa-w-private-gym" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\the-limasan-authentic-2br-villa-80m-from-beach" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\the-mountain-breath-sidemen" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\the-peak-8-villa-nusa-dua-nusa-dua" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\the-taman-sari-cabin-sidemen" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\the-view-2br-luxury-villa" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\the-view-2br-luxury-villa-uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\three-hita-karana-nature-3br-jungle-retreat-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\thula-1" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\thula-2" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\tropical-2br-villa-with-private-pool-in-canggu-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\ubud-luxury-resort-5br-w-gym-rice-field-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\ubud-sweet-days-2br-lush-jungle-view-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\ubud-villa-w-80m-pool-rice-views" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\veni-vidi-vici-with-sports-facilities-spectacular-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-aelora" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-alegria-2-br-rice-field-serenity-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-amartya-f7" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-amartya-f8" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-anna-lou-1br-boho-escape-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-arara-6br-private-sanctuary-for-families" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-asri-1br-romantic-w-bathtub-near-to-beach" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-bayu-bingin-jl-bangbang-metuug-no80361-pecatu-kec-kuta-sel-kabupaten-badung-bali-80361-indonesie" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-cahaya" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-cassie-2-br-your-private-haven-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-castagnou-5br-wstunning-rice-field-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-celavie-4br-villa-in-tumbakbayuh" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-crescence-paradise-3-br-ubud-hidden-gem" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-destiny" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-dhiantus-3br-modern-wprivate-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-domus-1-2-br-live-the-uluwatu-life" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-domus-3-2-br-embrace-the-uluwatu-lifestyle" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-dua-baskom-3br-dream-w-pool-jungle-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-eden-rock-5br-with-jungle-view-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-flori" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-gabrielle-4br-w-pool-jungle-view-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-gian-minima-4br-w-bathtub-infinity-pool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-glentana" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-jalak-5-br-w-infinity-pool-gym-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-jimeste-3br-winfinity-pool-gym-bathtub" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-kevin-3br-private-villa-seseh" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-kiri-modern-2br-villa-rooftop-pool-seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-koma-3br-winfinity-pool-bathtub-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-kuala-1" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-kuala-2" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-kumarajiva" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-layang-3-br-a-family-friendly-oasis-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-luna-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-madu-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-mandala-3-br-ubud-retreat-w-private-pool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-mare" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-maya-baystylish-5br-pool-w-lush-jungle-view" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-mimosa" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-nuq" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-nwantiti-4br-w-yoga-shala-infinity-pool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-pacifida-6br-ubud-retreat-with-spa-gym" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-pande-3br-with-lagoon-pool-sauna-retreat" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-ricarda-3br-jungle-view-yoga-space-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-sagapo-2" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-saiko-3-br-winfinity-pool-sunken-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-samsara" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-santai-aja" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-serenity-5br-winfinity-pool-yoga-shala" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-shiva-2-br-haven-amidst-ubuds-rice-fields" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-sidhi-samadhi" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-sirarosa" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-slide-5br-winfinity-pool-gym-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-sol-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-swannelli-4br-with-pool-rice-field-views" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-teman-3-br-touch-of-paradise-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-tibrava-umalas-3br-wprivate-pool-in-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-uluma" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-vertical-garden-5br-winfinity-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-veryhan-2br-winfinity-pool-bathtub-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-vivere-2br-villa-w-private-infinity-pool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-welcome-3br-with-infinity-pool-in-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villa-white-pepper-2br-canggu-canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villasagapo1" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villawatu-jaya" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\villawatu-stella" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\wk-3br-family-friendly-pool-scooters-provided" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\yasmin-villa-ubud-2br" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villa\zen-paradise-6br-family-villa-wyoga-shala-ubud" -Recurse -Force -ErrorAction SilentlyContinue

# --- old area pages (built from virtual villas) ---
Remove-Item -LiteralPath "villas\canggu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\kecamatan-ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\mengwi" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\seminyak" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\seseh" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\sidemen" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\south-kuta" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\sukawati" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\tampaksiring" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\ubud" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\uluwatu" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "villas\umalas" -Recurse -Force -ErrorAction SilentlyContinue

# --- price index page (was built from fake data; will be regenerated when real prices exist) ---
Remove-Item -LiteralPath "bali-villa-prices" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "data\price-index.json" -Force -ErrorAction SilentlyContinue

Write-Host "Done. Villa page folders remaining:" (Get-ChildItem villa -Directory | Measure-Object).Count
